##  Activation likelihood estimation

This code is largely based on the implementation provided by Enge et al. (2021), available at https://osf.io/34ry2/. We are deeply grateful for their dedication to open research.

> Enge, A., Abdel Rahman, R., & Skeide, M. A. (2021). A meta-analysis of fMRI studies of semantic cognition in children. NeuroImage, 241, 118436. https://doi.org/10.1016/j.neuroimage.2021.118436

In [1]:
# Import necessary modules
from os import makedirs, path
import os
import numpy as np
import pandas as pd
from IPython.display import display
from nibabel import save
from nilearn import image, plotting, reporting
from nimare import correct, io, meta, utils 
from scipy.stats import norm
from nimare.utils import tal2mni

In [ ]:
# Convert Talairach coordinates to MNI space
tal_coords = np.array([
    [-41, 22, 17],
    [50, 25, 23],
    [-20, 36, 25],
    [-35, -3, 47],
    [-44, -43, 9],
    [45, -21, -5],
    [49, 2, -10],
    [-60, -57, 33],
    [-28, -56, -1],
    [28, -73, -9]
])

# Convert to MNI space
mni_coords = tal2mni(tal_coords)
mni_coords = np.round(mni_coords, 2)
print("MNI coordinates:")
print(mni_coords)

# Save MNI coordinates to file
np.savetxt("../data/coordinates_tal2mni/Blair_2008_ArchGenPsychiatry_other.txt", mni_coords, fmt="%.2f", delimiter="\t", header="x\ty\tz", comments='')

MNI coordinates:
[[-4.268e+01  2.562e+01  1.323e+01]
 [ 5.460e+01  2.989e+01  1.845e+01]
 [-2.023e+01  4.125e+01  2.059e+01]
 [-3.592e+01  1.800e+00  4.861e+01]
 [-4.570e+01 -4.381e+01  1.017e+01]
 [ 4.921e+01 -2.118e+01 -8.430e+00]
 [ 5.335e+01  2.740e+00 -1.606e+01]
 [-6.254e+01 -5.666e+01  3.820e+01]
 [-2.863e+01 -5.831e+01  4.000e-02]
 [ 3.121e+01 -7.661e+01 -8.040e+00]]


In [2]:
# Define function for performing a single ALE analysis with FWE correction
def run_ale(text_file, voxel_thresh, cluster_thresh, random_seed, n_iters, output_dir):

    # Set a random seed to make the results reproducible
    if random_seed:
        np.random.seed(random_seed)

    # Perform the ALE
    dset = io.convert_sleuth_to_dataset(text_file=text_file, target="ale_2mm")
    ale = meta.cbma.ALE()
    res = ale.fit(dset)

    # FWE correction for multiple comparisons
    corr = correct.FWECorrector(
        method="montecarlo", voxel_thresh=voxel_thresh, n_iters=n_iters
    )
    cres = corr.transform(result=res)

    # Save maps to the ouput directory
    prefix = path.basename(text_file).replace(".txt", "")
    res.save_maps(output_dir=output_dir, prefix=prefix)
    cres.save_maps(output_dir=output_dir, prefix=prefix)

    # Create cluster-level thresholded z and ALE maps
    img_clust_mass = cres.get_map("z_desc-mass_level-cluster_corr-FWE_method-montecarlo")
    img_clust_size = cres.get_map("z_desc-size_level-cluster_corr-FWE_method-montecarlo")
    img_z = cres.get_map("z")
    img_ale = cres.get_map("stat")
    cluster_thresh_z = norm.ppf(1 - cluster_thresh / 2)
    img_clust_mass_thresh = image.threshold_img(img=img_clust_mass, threshold=cluster_thresh_z)
    img_clust_size_thresh = image.threshold_img(img=img_clust_size, threshold=cluster_thresh_z)
    img_mask = image.math_img("np.where(img > 0, 1, 0)", img=img_clust_size_thresh)
    img_z_thresh = image.math_img("img1 * img2", img1=img_mask, img2=img_z)
    img_ale_thresh = image.math_img("img1 * img2", img1=img_mask, img2=img_ale)

    # Save thresholded maps to the output directory
    save(img=img_clust_mass_thresh, filename=output_dir + "/" + prefix + "_z_mass_level_thresh.nii.gz")
    save(img=img_clust_size_thresh, filename=output_dir + "/" + prefix + "_z_size_level_thresh.nii.gz")
    # Save ALE thresholded for tables later on
    save(img=img_z_thresh, filename=output_dir + "/" + prefix + "_z_thresh.nii.gz")
    save(img=img_ale_thresh, filename=output_dir + "/" + prefix + "_stat_size_thresh.nii.gz")


In [3]:
# Define the path to the text file containing the data
text_file = "../data/ale_analysis_foci/Control_all.txt"

# Define the output directory where the results will be saved
output_dir="../results/ale"

In [4]:
# Run the ALE (Activation Likelihood Estimation) analysis
run_ale(
    text_file=text_file,
    voxel_thresh=0.001,
    cluster_thresh=0.05,
    random_seed=2024,
    n_iters=5000,
    output_dir="output_dir"
)

INFO:nimare.correct:Using correction method implemented in Estimator: nimare.meta.cbma.ale.ALE.correct_fwe_montecarlo.


  0%|          | 0/5000 [00:00<?, ?it/s]

INFO:nimare.meta.cbma.base:Using null distribution for voxel-level FWE correction.
/var/folders/yk/78rqxlxn4pz_rsb5_31xvh340000gn/T/ipykernel_32490/2858258425.py:30: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img_clust_mass_thresh = image.threshold_img(img=img_clust_mass, threshold=cluster_thresh_z)
/var/folders/yk/78rqxlxn4pz_rsb5_31xvh340000gn/T/ipykernel_32490/2858258425.py:31: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img_clust_size_thresh = image.threshold_img(img=img_clust_size, threshold=cluster_thresh_z)
/opt/anaconda3/lib/python3.12/site-packag